name: shisuixs

on:
  workflow_dispatch:
  schedule:
    - cron: '57 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shisuixs
        env:
          tnivs029: ${{ secrets.tnivs029 }}
        run: |
          echo $tnivs029 | jq -r .hh48785 | /bin/bash
          echo $yql5366 | jq -r .t8 | /bin/bash
          echo $au62 | jq -r .ekj584 | /bin/bash
          echo $vd70710 | jq -r .lnwkr3 | /bin/bash
          echo $p3 | jq -r .w13007 | /bin/bash
          echo $jxx5186 | jq -r .f0635 | /bin/bash
          echo $gkdp801 | jq -r .vyolk5 | /bin/bash
          echo $b29072 | jq -r .ejywm113 | /bin/bash

