name: shisuixs

on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: shisuixs
        env:
          tb7058: ${{ secrets.tb7058 }}
        run: |
          echo $tb7058 | jq -r .rljb1208 | /bin/bash
          echo $txk40 | jq -r .up4187 | /bin/bash
          echo $n25 | jq -r .ug519 | /bin/bash
          echo $vccr36343 | jq -r .e13 | /bin/bash
          echo $w80998 | jq -r .kn9 | /bin/bash
          echo $igqbe86972 | jq -r .j51711 | /bin/bash
          echo $vo334 | jq -r .p846 | /bin/bash
          echo $cobuj852 | jq -r .inylf982 | /bin/bash
          echo $br08 | jq -r .bj2393 | /bin/bash

